### ISSUE TITLE
rawhide/ffmpeg/opencv problem

### ISSUE THREAD

**Issue by ghost** [UnitedRPMs/ffmpeg#1]
https://unitedrpms.github.io/

> Repository with additional software for Fedora 24 and Fedora 25

Fedora 25=Fedora rawhide
Error: nothing provides libopencv_core.so.2.4()(64bit) needed by ffmpeg-libs-3.0.1-1.fc24.x86_64

**Comment by paulcarroty** [comment]
@region51 you must downgrade opencv & opencv-core to 2.4.12.3 http://koji.fedoraproject.org/koji/buildinfo?buildID=740689

or

@kuboosoft @sergiomb2 what about our plans to rawhide? Open second front?

**Comment by sergiomb2** [comment]
I think the the plan is disable opencv on ffmpeg builds on rawhide , until ffmpeg have a fix for opencv-3.1. 
I'm working on Opencv package in Fedora , we decide update to 3.1 on rawhide , but we also plan/ want merge it into F24 before GA (General Availability). Ffmpeg, looks to me, that is a blocker, 
meanwhile you may open a bug report upstream i.e. in ffmpeg project, they will do support for opencv-3, almost certain.

**Comment by paulcarroty** [comment]
@sergiomb2 I agree. 

@kuboosoft what you think? Ffmpeg is completely your package.

**Comment by kuboosoft** [comment]
mmm if opencv  is disabled;  exist others programs affected; generally "video editors" Why not make a updated opencv here? besides a conditional build enabled here with opencv?

**Comment by paulcarroty** [comment]
@kuboosoft F24 and F25 use the different versions of opencv. The highest version can't be compiled in F24 if you want to create a `compat-` library.

**Comment by sergiomb2** [comment]
> exist others programs affected; generally "video editors" 

what programs ?

the real fix is build ffmpeg opencv-3.1

**Comment by paulcarroty** [comment]
@sergiomb2 and create repo for F25? F24 now use [2.4.12](http://koji.fedoraproject.org/koji/packageinfo?packageID=2692).

**Comment by sergiomb2** [comment]
I don't know , we need to have one ffmpeg for F24 and one ffmpeg for F25 , at least , but duplicate all for me is a bad idea , upload all this stuff to googledrive give me many work , duplicate the work is not good idea for me .

**Comment by kuboosoft** [comment]
@sergiomb2 no hosted in fedora project...they use ffmpeg and opencv; if opencv 3.1 is available for Fedora 25; then why no make a repository here with the current version and rebuilt ffmpeg? @paulcarroty opencv-compat/opencv2; sound fine; but is necessary check if no affect the official release.

**Comment by paulcarroty** [comment]
>  then why no make a repository here with the current version and rebuilt ffmpeg?

@kuboosoft because we need to rebuild the all ffmpeg depends for F25, no? It will be easy with private koji/copr.

**Comment by kuboosoft** [comment]
@paulcarroty ffmeg 3.0.2 is available now ;) is the moment haha

**Comment by paulcarroty** [comment]
@kuboosoft yep, @region51 request it. With new ffmpeg we need also rebuild chromium, kdenlive and maybe something others.

**Comment by kuboosoft** [comment]
@paulcarroty  how to test all ? Well, rebuilt ffmpeg, and install all packages hosted here ;); is the way for me... using mock and detect if exist lost dependencies

**Comment by paulcarroty** [comment]
So, I admit the next scheme: our Rawhide users add F24 repo plus special repo with fixes for F25.

> how to test all ?

Check depends with dnf and install if it's correctly.

**Comment by sergiomb2** [comment]
> With new ffmpeg we need also rebuild chromium, kdenlive and maybe something others.

no, we just need rebuild when have soname bump , (ffmpeg2.8 -> ffmpeg 3 ) which isn't the case

**Comment by kuboosoft** [comment]
@sergiomb2 maybe we need a database with all packages dependent with ffmpeg.
similar...
https://www.archlinux.org/packages/extra/x86_64/ffmpeg/

**Comment by paulcarroty** [comment]
@kuboosoft 

```
# dnf repoquery --whatrequires  ffmpeg
Last metadata expiration check: 1:17:53 ago on Fri May  6 21:34:50 2016.
idjc-0:0.8.15-1.fc24.x86_64
kdenlive-0:15.12.2-2.fc24.x86_64
mjpegtools-0:2.1.0-6.fc24.x86_64

# dnf repoquery --whatrequires  ffmpeg-libs
Last metadata expiration check: 1:18:36 ago on Fri May  6 21:34:50 2016.
spotify-client-0:1.0.27-1.fc24.x86_64

```

**Comment by sergiomb2** [comment]
http://rpmfusion.org/ImportantDependencyLists

but just when so bump

**Comment by kuboosoft** [comment]
@sergiomb2  @paulcarroty recommendations?, updates minors for ffmpeg, for stability? or Mass rebuild constantly...

**Comment by kuboosoft** [comment]
I solved the issue; minor changes, happy day for all ;) only I need update libav ;)

**Comment by paulcarroty** [comment]
@kuboosoft, wow, great work. Guess this will be one reason of my Copr ban :smile:

**Comment by kuboosoft** [comment]
@paulcarroty is time you work with mock... and avoid ban with Copr!

**Comment by paulcarroty** [comment]
Merged to RPMs repo.

**Comment by kuboosoft** [comment]
@paulcarroty I applied some changes to vlc,  I will update the next hours... now is easy make mass rebuild ;)
